blocked-commands:
  - example_command1
  - example_command2
  - example_command3
  
messages:
  blocked-command: "&5TCommandBlocker &e> &cYou do not have permission to execute this command."
  config-reloaded: "&5TCommandBlocker &e> &aConfiguration reloaded correctly."
  no-permission-message: "&5TCommandBlocker &e> &cYou do not have permission to use this command."
  version-message: "&5TCommandBlocker &e> &aVersion: &b{version}"
